name: neat.graphics
favicon: null
layout_spectrum: 0.1804231491405517
typography_spectrum: 0.40496
title: neat.graphics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#c5bfc1'
    - '#383732'
    - '#5b6a67'
    - '#a14027'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
