name: neat.graphics
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07617
title: neat.graphics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090810'
    - '#f6f7f2'
    - '#a7ab88'
    - '#727155'
    - '#5b2d1d'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
